#!/usr/bin/env python3
"""
Generate a simple Cornell Box geometry as OBJ file for Quantiloom M1 testing.

Output: cornell_box.obj (ASCII wavefront format)
"""

import os

def generate_cornell_box(output_path):
    """
    Generate Cornell Box with 5 walls:
    - Floor (gray)
    - Ceiling (gray)
    - Back wall (gray)
    - Left wall (red)
    - Right wall (green)

    Dimensions: 2x2x2 cube centered at origin
    """

    obj_content = """# Cornell Box for Quantiloom M1
# Generated by generate_cornell_box.py

# Vertices (corners of the box)
v -1.0 -1.0 -1.0
v  1.0 -1.0 -1.0
v  1.0 -1.0  1.0
v -1.0 -1.0  1.0
v -1.0  1.0 -1.0
v  1.0  1.0 -1.0
v  1.0  1.0  1.0
v -1.0  1.0  1.0

# Normals
vn  0.0  1.0  0.0  # Up (floor/ceiling)
vn  0.0 -1.0  0.0  # Down
vn  0.0  0.0  1.0  # Front
vn  0.0  0.0 -1.0  # Back
vn -1.0  0.0  0.0  # Left
vn  1.0  0.0  0.0  # Right

# Floor (gray)
g floor
f 1//1 2//1 3//1
f 1//1 3//1 4//1

# Ceiling (gray)
g ceiling
f 5//2 8//2 7//2
f 5//2 7//2 6//2

# Back wall (gray)
g back_wall
f 1//4 4//4 8//4
f 1//4 8//4 5//4

# Left wall (red)
g left_wall
f 1//5 5//5 6//5
f 1//5 6//5 2//5

# Right wall (green)
g right_wall
f 4//6 3//6 7//6
f 4//6 7//6 8//6
"""

    with open(output_path, 'w') as f:
        f.write(obj_content)

    print(f"✓ Cornell Box generated: {output_path}")
    print(f"  Vertices: 8")
    print(f"  Triangles: 10 (5 quads)")
    print(f"  Dimensions: 2x2x2 cube")

if __name__ == "__main__":
    # Output to assets/scenes/
    output_dir = os.path.join(os.path.dirname(__file__), "../../assets/scenes")
    os.makedirs(output_dir, exist_ok=True)

    output_path = os.path.join(output_dir, "cornell_box.obj")
    generate_cornell_box(output_path)
